apiVersion: v1
kind: Service
metadata:
  name: {{ include "playground-cli.fullname" . }}
  labels:
{{ include "playground-cli.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: h2-playground-cli
  selector:
    app.kubernetes.io/name: {{ include "playground-cli.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
