{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "playground-cli.serviceAccountName" . }}
  labels:
{{ include "playground-cli.labels" . | indent 4 }}
{{- end -}}
