{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gloo-playground.serviceAccountName" . }}
  labels:
{{ include "gloo-playground.labels" . | indent 4 }}
{{- end -}}
