{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "companion.serviceAccountName" . }}
  labels:
{{ include "companion.labels" . | indent 4 }}
{{- end -}}
